export const APP_WRITE_ID = '6805101a00288079787f'
export const DB_ID = 'deals'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
